# Hadolint Configuration for DrLaBulle
failure-threshold: error

# Rule overrides
override:
  error:
    - DL3006 # Forbid untagged base images
  warning:
    - DL3008 # Pin versions in apt-get install
    - DL3018 # Pin versions in apk add